# Generated by Django 6.0.2 on 2026-02-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('CHEGADA', 'Aguardando Triagem'), ('TRIAGEM', 'Em Triagem'), ('AGUARDANDO_MEDICO', 'Aguardando Médico'), ('CHAMADO_MEDICO', 'Chamado para Médico'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='CHEGADA', max_length=30)),
                ('prioridade', models.CharField(blank=True, choices=[('VERMELHO', 'Emergência'), ('LARANJA', 'Muito Urgente'), ('AMARELO', 'Urgente'), ('VERDE', 'Pouco Urgente'), ('AZUL', 'Não Urgente')], max_length=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chamado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='patients.patient')),
            ],
        ),
    ]
