# Generated by Django 6.0.2 on 2026-02-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaatendimento',
            name='local_atendimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichaatendimento',
            name='status',
            field=models.CharField(choices=[('CHEGADA', 'Aguardando Triagem'), ('CHAMADO_TRIAGEM', 'Chamado para Triagem'), ('TRIAGEM', 'Em Triagem'), ('AGUARDANDO_MEDICO', 'Aguardando Médico'), ('CHAMADO_MEDICO', 'Chamado para Médico'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='CHEGADA', max_length=30),
        ),
    ]
