# Generated by Django 6.0.2 on 2026-02-12 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_fichaatendimento_local_atendimento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaatendimento',
            options={'ordering': ['-prioridade', 'criado_em'], 'verbose_name': 'Ficha de Atendimento', 'verbose_name_plural': 'Fichas de Atendimento'},
        ),
        migrations.AddField(
            model_name='fichaatendimento',
            name='frequencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaatendimento',
            name='medico_atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_medicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaatendimento',
            name='observacoes_triagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaatendimento',
            name='pa_diastolica',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pressão Diastólica'),
        ),
        migrations.AddField(
            model_name='fichaatendimento',
            name='pa_sistolica',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pressão Sistólica'),
        ),
        migrations.AddField(
            model_name='fichaatendimento',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='fichaatendimento',
            name='status',
            field=models.CharField(choices=[('CHEGADA', 'Aguardando Triagem'), ('CHAMADO_TRIAGEM', 'Chamado para Triagem'), ('EM_TRIAGEM', 'Em Triagem'), ('TRIADO', 'Aguardando Encaminhamento Médico'), ('AGUARDANDO_MEDICO', 'Aguardando Médico'), ('CHAMADO_MEDICO', 'Chamado para Médico'), ('EM_ATENDIMENTO', 'Em Atendimento Médico'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='CHEGADA', max_length=30),
        ),
    ]
